#pragma once

#define LISTEN_SERVER_PORT 1313

#define DISPLAY_QUADRANT_TOP    0
#define DISPLAY_QUADRANT_RIGHT  1
#define DISPLAY_QUADRANT_BOTTOM 2
#define DISPLAY_QUADRANT_LEFT   3
#define NUM_DISPLAY_QUADRANTS   4

#define NUM_KEYS 256

#define MAX_VIEWPORT_WIDTH 2048
#define MAX_VIEWPORT_HEIGHT 2048

#define CENTER_OFFSET 0.0f

#define UI_X_OFFSET -0.05f
#define UI_Y_OFFSET 1.0f
#define UI_WIDTH 2*UI_X_OFFSET
#define UI_HEIGHT UI_WIDTH

#define ICON_WIDTH 128
#define ICON_HEIGHT 128
